### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by brunnels** [conklech/ReefAngel-PIO#2]
Trying to get it building with the latest pio.  Went to with standard minimal ra plus main.cpp but DS1307RTC is failing Wire.h include.

**Comment by brunnels** [comment]
moving `#include <DS1307RTC.h>` from RA_Wifi.cpp into RA_Wifi.h got it building.  Will see if it continues to work as I add modules and config

**Comment by conklech** [comment]
I'd be happy to accept a pull request, but I haven't been maintaining this
for a while. Thanks!

**Comment by brunnels** [comment]
I'll send a pr for the readme.md and maybe some platformio.ini tweaks but I needed to tweak the base RA RA_Wifi libs so I'll send a PR to Roberto.
